
ami-name = "CentOS-Stream-ec2-8-20220919.1.x86_64-*"
region = "us-east-1"
instance_type = "t2.small"
disk_size = "100"
resource = "spotfire-server"
postgres_version = "13"
mount_dir = "mnt/spotfire"
hostname = "spotfire-server"
s3_bucket = "test-spotfire"
